### ISSUE TITLE
Logout with multi guard ?

### ISSUE THREAD

**Issue by jeanali** [painlesscode/breeze-multiauth#2]
When I create admin and user guards & login both user and admin in the same browser and then just logout one of them it destroy both session for user and admin too>!

**Comment by HazzazBinFaiz** [comment]
When try to logout from any guard, it invalidates the session.
That's why you are logged out from other guards too.

You can fix this problem by commenting those lines for every guard (both user and admin) .
You can find them in app/Http/Controllers/Auth/AuthenticatedSessionController.php (for user) and  app/Http/Controllers/Admin/Auth/AuthenticatedSessionController.php (for admin)
https://github.com/painlesscode/breeze-multiauth/blob/72fcb2fd1b244a11e6863905cc0a4b86dc886e4b/stubs/App/Http/Controllers/Auth/AuthenticatedSessionController.php#L48-L50
